#!/usr/bin/env python3
"""Regenerate ./.clangd so clangd gives full Arduino IntelliSense for .ino/.cpp/.h.

Usage: python3 .vscode/gen-clangd.py <sketch-dir> [fqbn]
Run via the VSCode task "Arduino: Refresh IntelliSense" (re-run after adding libraries).
"""
import json, shlex, os, sys, subprocess

sketch = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else ".")
fqbn = sys.argv[2] if len(sys.argv) > 2 else "arduino:renesas_uno:nanor4"
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # workspace root
build = os.path.join(sketch, "build")

# 1. (re)generate the compilation database
subprocess.run(["arduino-cli", "compile", "-b", fqbn,
                "--only-compilation-database", "--build-path", build, sketch], check=True)

db = json.load(open(os.path.join(build, "compile_commands.json")))
entry = next(e for e in db if e["file"].endswith(".ino.cpp"))
cmd = entry.get("command") or " ".join(entry["arguments"])

def expand(tokens):
    out = []
    for t in tokens:
        if t.startswith("@") and os.path.isfile(t[1:]):
            out += expand(shlex.split(open(t[1:]).read()))
        else:
            out.append(t)
    return out

toks = expand(shlex.split(cmd))
compiler = toks[0]  # the exact compiler arduino-cli used for THIS board (avr, arm, xtensa)
includes, defines, std, iprefix = [], [], None, None
i = 0
while i < len(toks):
    a = toks[i]; nxt = toks[i + 1] if i + 1 < len(toks) else None
    if a.startswith("-std="): std = a
    elif a == "-iprefix": iprefix = nxt; i += 1
    elif a.startswith("-iprefix"): iprefix = a[8:]
    elif a.startswith("-iwithprefixbefore"):
        v = nxt if a == "-iwithprefixbefore" else a[18:]
        if a == "-iwithprefixbefore": i += 1
        if iprefix: includes.append(os.path.normpath(iprefix + "/" + v.lstrip("/")))
    elif a == "-I": includes.append(nxt); i += 1
    elif a.startswith("-I"): includes.append(a[2:])
    elif a == "-isystem": includes.append(nxt); i += 1
    elif a.startswith("-isystem"): includes.append(a[8:])
    elif a == "-D": defines.append(nxt); i += 1
    elif a.startswith("-D"): defines.append(a[2:])
    i += 1

inc = list(dict.fromkeys(p for p in includes if os.path.isdir(p)))
defs = list(dict.fromkeys(defines))

L = ["# AUTO-GENERATED by .vscode/gen-clangd.py, do not hand-edit.",
     "# Gives clangd full Arduino IntelliSense (.ino/.cpp/.h). Re-run the",
     "# 'Arduino: Refresh IntelliSense' task after adding libraries.",
     "CompileFlags:",
     "  Compiler: " + compiler,
     "  Add:",
     "    - -include", "    - Arduino.h", "    - -xc++"]
if std: L.append("    - " + std)
for x in defs: L.append("    - -D" + x)
for x in inc: L.append("    - -I" + x)
# Strip arch-specific codegen flags clangd's parser may not understand
# (arm: -mcpu/-mthumb/-mfloat-abi/-mfpu/-mabi ; avr: -mmcu ; xtensa/esp: -mlongcalls/-mtext-section-literals).
L += ["  Remove:", "    - -mcpu=*", "    - -mthumb", "    - -mfloat-abi=*",
      "    - -mfpu=*", "    - -mabi=*", "    - -mmcu=*", "    - -mlongcalls",
      "    - -mtext-section-literals", "    - -mno-*", "    - --param=*"]
open(os.path.join(root, ".clangd"), "w").write("\n".join(L) + "\n")
print(f"Wrote {root}/.clangd  ({len(inc)} include dirs, {len(defs)} defines)")
